spring:
  # DataSource Config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-eovdqrbo.sql.tencentcdb.com:23292/cohelp?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: 'cohelp'
    password: 'cohelp123456..'

  # MailConfig
  mail:
    host: smtp.qq.com
    username: 2280867329@qq.com
    password: hfntazmljtjdeccb
    port: 587

  # ImageConfig
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-circular-references: true
prop:
  upload-folder: C:/Users/靑/Desktop/项目/Co-Help/CoHelp/Server/image/

server:
  port: 9090