spring:
  # DataSource Config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cohelp?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: 'root'
    password: '011205'

  # MailConfig
  mail:
    host: smtp.qq.com
    username: 3132701082@qq.com
    password: dcxswjojxzgideac
    port: 587

  # ImageConfig
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-circular-references: true

  ## COS 配置
  tengxun:
    SecretId: 'AKIDmQrFmuHRN7f18B493ormU1gFkAWioleQ'
    SecretKey: 'gDznqdJuhUGzXzH2gBXnwvlR5Z4RiohU'
    region: 'ap-shanghai'
    url: 'https://jp-typora-1310703557.cos.ap-shanghai.myqcloud.com/'
    bucketName: 'jp-typora-1310703557'